import { v4 as uuidv4 } from 'uuid';

const products = [
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'Iceland Ggreen',
    prix: 35,
    dimensions: '25x30',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1824.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'The Old House',
    prix: 35,
    dimensions: '25x40',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1825.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'The Dirty House',
    prix: 35,
    dimensions: '40x30',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1826.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'The Ugly House',
    prix: 25,
    dimensions: '55x30',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1827.jpg',
    status: 'sold',
  },
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'Rue d\'Alternatibounce',
    prix: 15,
    dimensions: '15x30',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1828.jpg',
    status: 'sold',
  },
  {
    product_id: uuidv4(),
    type: 'painting',
    name: 'Le Château de la Montagne inversée',
    prix: 55,
    dimensions: '25x50',
    support: 'paper',
    technic: 'watercolor',
    image_url: '/img/IMG_1829.jpg',
    status: 'sold',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'La Meuf sur la barre',
    prix: 65,
    dimensions: '26x30',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1830.jpg',
    status: 'sold',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'Le Vieux qui Fume',
    prix: 60,
    dimensions: '40x30',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1831.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'Le Mec qui tend la main',
    prix: 35,
    dimensions: '25x30',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1832.jpg',
    status: 'sold',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'Les Deux Mecs',
    prix: 61,
    dimensions: '55x50',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1835.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'Le Couple',
    prix: 90,
    dimensions: '40x40',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1836.jpg',
    status: 'available',
  },
  {
    product_id: uuidv4(),
    type: 'drawing',
    name: 'La Vieille Ruine',
    prix: 85,
    dimensions: '15x50',
    support: 'paper',
    technic: 'pencil',
    image_url: '/img/IMG_1837.jpg',
    status: 'sold',
  },
];

export { products };
